name: resolve_windows_shortcut
description: Resolve target paths of Windows Shortcut (.lnk) files.
version: 2.0.0
repository: https://github.com/emartineau/resolve_windows_shortcut

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
